name: Download

on:
  workflow_dispatch:
    inputs:
      url:
        description: "Enter URL"
        required: true

jobs:
  download:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install yt-dlp
        run: |
          python -m pip install --upgrade pip
          pip install -U yt-dlp

      - name: Create downloads folder
        run: mkdir -p downloads

      - name: Download media
        run: |
          yt-dlp \
          --geo-bypass \
          --no-check-certificates \
          -o "downloads/%(title)s.%(ext)s" \
          "${{ github.event.inputs.url }}"

      - name: Commit downloaded file
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add downloads/

          git commit -m "Add downloaded media" || echo "Nothing to commit"

          git push
