name: Telegram Downloader

on:
  workflow_dispatch:
    inputs:
      url:
        description: "Telegram public link"
        required: true

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Install yt-dlp
        run: |
          pip install yt-dlp

      - name: Download from Telegram
        run: |
          mkdir downloads
          cd downloads
          yt-dlp "${{ github.event.inputs.url }}"

      - name: Upload file
        uses: actions/upload-artifact@v4
        with:
          name: telegram-download
          path: downloads/
