name: download

on:
  workflow_dispatch:
    inputs:
      url:
        description: "Video URL"
        required: true

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Git LFS
        run: |
          git lfs install

      - name: Install yt-dlp
        run: |
          pip install -U yt-dlp

      - name: Create download folder
        run: |
          mkdir -p downloads

      - name: Download media
        run: |
          yt-dlp \
          --no-playlist \
          -o "downloads/%(title)s.%(ext)s" \
          "${{ github.event.inputs.url }}"

      - name: Track large files with Git LFS
        run: |
          git lfs track "downloads/*"
          git add .gitattributes

      - name: Commit downloaded file
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add downloads/

          git commit -m "Add downloaded media" || echo "Nothing to commit"

          git push
